build:
  image: node
  commands:
    - npm install
    - npm run fontawesome
    - npm run build:production
cache:
  mount:
    - node_modules
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xiaolu-img/xiaolusys-ui
    tag: mall
    file: Dockerfile
    mirror: https://n5fb0zgg.mirror.aliyuncs.com
    when:
      branch: master
deploy:
  ssh:
    host: 
      - staging.xiaolumm.com
      - sale.xiaolumm.com
    when:
      branch: master
    user: root
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys-ui:mall
      - docker run --rm --volumes-from=static registry.aliyuncs.com/xiaolu-img/xiaolusys-ui:mall cp -rf mall /data/mall

